# Generated by Django 2.2.7 on 2019-11-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191115_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermailaddress',
            old_name='is_deleteWd',
            new_name='is_deleted',
        ),
    ]
