# Generated by Django 2.2.7 on 2019-11-16 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191115_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermailaddress',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='customertypemap',
            old_name='type',
            new_name='customertype',
        ),
    ]
