# Generated by Django 2.2.7 on 2019-11-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191116_0441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
